# Generated by Django 4.0.6 on 2022-07-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_completo', models.CharField(max_length=255)),
                ('Conta_corrente', models.CharField(max_length=6)),
                ('Agencia', models.CharField(max_length=4)),
                ('Senha', models.CharField(max_length=6)),
                ('CPF', models.CharField(max_length=11)),
                ('Endereço', models.CharField(max_length=255)),
                ('CEP', models.CharField(max_length=8)),
                ('Telefone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
